name: Deployment Workflow

on:
  push:
    branches:
      - development  # Trigger on push to the 'development' branch
  workflow_dispatch:

jobs:
  build:
    name: "@mindfiredigital/pivothead_core"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm  # Install pnpm globally

      - name: Install dependencies
        run: pnpm install  # Use pnpm to install dependencies

      - name: Build application
        run: pnpm run build  # Use pnpm to run the build

      - name: Set Git user name and email
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Merge development into main and push
        run: |
          git fetch origin main  # Fetch the latest 'main' branch to ensure it's up to date
          git checkout main  # Switch to the 'main' branch
          git merge development --no-ff -m "Merge development into main"  # Merge 'development' into 'main'
          git push origin main  # Push the changes to 'main' branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authentication token for GitHub

  create-github-release:
    name: Create GitHub release document and publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm
        run: npm install -g pnpm  # Install pnpm globally

      - name: Install dependencies
        run: pnpm install  # Use pnpm to install dependencies

      - name: Semantic Release and npm release
        run: |
          npx semantic-release  # This will handle versioning, changelog, and npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Authentication token for npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authentication token for GitHub

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: core-build-zip  # Name of the artifact
          path: ./packages/core/dist  # Path to the build folder to zip and upload
