name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: '@mindfiredigital/pivothead_core'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@9.15.2  # Install specific pnpm version globally

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Restore changes in pnpm lock
        run: git restore pnpm-lock.yaml  # Ensure lockfile isn't modified after install

      - name: Build application
        run: pnpm run build  # Run build command

      - name: Set Git user name and email
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

  create-github-release:
    name: Create GitHub release and publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@9.15.2  # Install the same pnpm version

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Restore changes in pnpm lock
        run: git restore pnpm-lock.yaml

      - name: Create changeset and version packages
        run: |
          pnpm add -g @changesets/cli  # Install changesets CLI globally
          pnpm changeset version       # Version packages based on changesets
          git add .
          git commit -m "Version packages"
          git push origin main

      - name: Publish to npm
        run: pnpm changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # NPM token for authentication

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.newVersion }}
          release_name: Release v${{ steps.version.outputs.newVersion }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: core-build-zip
          path: ./packages/core/dist
