name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Set authentication token globally

jobs:
  build:
    name: '@mindfiredigital/pivothead_core'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          cat ~/.npmrc  # Debugging: Print to check if the token is set

      - name: Verify npm authentication
        run: |
          echo "Checking npm authentication..."
          npm whoami || echo "Not logged into npm. Check NPM_TOKEN."

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm -v
          node -v
          npm -v

      - name: Install dependencies with pnpm (Debug)
        run: |
          pnpm config set registry https://registry.npmjs.org
          pnpm config set fetch-retries 3
          pnpm config set fetch-timeout 60000
          pnpm config set loglevel debug
          pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Set Git user name and email
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

  create-github-release:
    name: Create GitHub release and publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Verify npm authentication
        run: |
          echo "Checking npm authentication..."
          npm whoami || echo "Not logged into npm. Check NPM_TOKEN."

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Create changeset and version packages
        run: |
          pnpm add -g @changesets/cli
          pnpm changeset version
          git add .
          git commit -m "Version packages"
          git push origin main

      - name: Publish to npm (Dry Run)
        run: pnpm changeset publish --dry-run
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm (Real)
        run: pnpm changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.newVersion }}
          release_name: Release v${{ steps.version.outputs.newVersion }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: core-build-zip
          path: ./packages/core/dist
